name: glfw
version: 1.0.2+1
description: Dart GLFW bindings
authors:
  - John McDole <codefu@google.com>
  - Jason Daly <dalyj@google.com>
  - Michael McLennan <nefario@google.com>
  - Harry Stern <hstern@google.com>
homepage:
environment:
  sdk: '>=2.3.0 <3.0.0'
dev_dependencies:
  args: '^1.5.1'
  path: '^1.6.2'
  pedantic: '1.7.0'
  quiver: '>=2.0.0 <3.0.0'
